spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eazybank
    username: docker
    password: docker
    hikari:
      schema: public
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true